.TH "gui.h" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <gtk/gtk.h>\fP
.br
\fC#include <glib.h>\fP
.br
\fC#include <gdk/gdkkeysyms.h>\fP
.br
\fC#include 'utils.h'\fP
.br
\fC#include 'controller.h'\fP
.br
\fC#include 'datamanager.h'\fP
.br
\fC#include 'tortellaprotocol.h'\fP
.br

.SS "Strutture dati"

.in +1c
.ti -1c
.RI "struct \fBtree_model\fP"
.br
.ti -1c
.RI "struct \fBpm_data\fP"
.br
.in -1c
.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBTOP\fP   0x01"
.br
.ti -1c
.RI "#define \fBBOTTOM\fP   0x02"
.br
.ti -1c
.RI "#define \fBCHAT\fP   0x03"
.br
.ti -1c
.RI "#define \fBPM\fP   0x04"
.br
.ti -1c
.RI "#define \fBONLINE\fP   'Online'"
.br
.ti -1c
.RI "#define \fBBUSY\fP   'Busy'"
.br
.ti -1c
.RI "#define \fBAWAY\fP   'Away'"
.br
.in -1c
.SS "Ridefinizioni di tipo (typedef)"

.in +1c
.ti -1c
.RI "typedef struct \fBtree_model\fP \fBtree_model\fP"
.br
.ti -1c
.RI "typedef struct \fBpm_data\fP \fBpm_data\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "gint \fBgui_close_window_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "void \fBgui_close_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "void \fBgui_open_chat_event\fP (GtkTreeView *treeview, GtkTreePath *\fBpath\fP, GtkTreeViewColumn *col, gpointer userdata)"
.br
.ti -1c
.RI "gint \fBgui_leave_chat_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_leave_pm_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_add_chat\fP (\fBu_int8\fP chat_id, char *chat_name)"
.br
.ti -1c
.RI "gint \fBgui_clear_chat_list\fP ()"
.br
.ti -1c
.RI "gint \fBgui_clear_buffer\fP (GtkTextView *widget)"
.br
.ti -1c
.RI "gint \fBgui_add_message\fP (GtkTextView *widget, gchar *msg)"
.br
.ti -1c
.RI "gint \fBgui_add_user_to_chat\fP (\fBu_int8\fP chat_id, \fBu_int8\fP id, char *user, \fBu_int1\fP status)"
.br
.ti -1c
.RI "gint \fBgui_del_user_from_chat\fP (\fBu_int8\fP chat_id, \fBu_int8\fP user_id)"
.br
.ti -1c
.RI "gint \fBgui_change_status\fP (\fBu_int8\fP user_id, char *status)"
.br
.ti -1c
.RI "gint \fBgui_open_conversation_event\fP (GtkTreeView *treeview, GtkTreePath *\fBpath\fP, GtkTreeViewColumn *col, gpointer userdata)"
.br
.ti -1c
.RI "gint \fBgui_open_about_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_set_to_online_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_set_to_busy_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_set_to_away_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_search_chat_event\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_send_text_message_event\fP (GtkWidget *widget, GdkEventKey *event, gpointer gdata)"
.br
.ti -1c
.RI "gint \fBgui_send_pm_message_event\fP (GtkWidget *widget, GdkEventKey *event, gpointer gdata)"
.br
.ti -1c
.RI "GtkWidget * \fBgui_create_users_list\fP (\fBu_int8\fP index)"
.br
.ti -1c
.RI "GtkWidget * \fBgui_create_chat_list\fP (\fBu_int8\fP index)"
.br
.ti -1c
.RI "GtkWidget * \fBgui_create_menu\fP (void)"
.br
.ti -1c
.RI "GtkWidget * \fBgui_create_text\fP (\fBu_int8\fP chat_id, int type, int msg_type)"
.br
.ti -1c
.RI "GtkWidget * \fBgui_create_searchbar\fP (void)"
.br
.ti -1c
.RI "gint \fBgui_create_chat_button\fP (GtkWidget *widget, gpointer gdata)"
.br
.ti -1c
.RI "int \fBgui_open_chatroom\fP (\fBu_int8\fP)"
.br
.ti -1c
.RI "int \fBgui_open_pm\fP (\fBu_int8\fP user_id, gchar *nickname)"
.br
.ti -1c
.RI "\fBtree_model\fP * \fBgui_get_tree_model\fP (\fBu_int8\fP chat_id)"
.br
.ti -1c
.RI "int \fBgui_add_msg_to_chat\fP (\fBu_int8\fP chat_id, char *msg)"
.br
.ti -1c
.RI "int \fBgui_add_msg_pm\fP (\fBu_int8\fP sender_id, char *msg)"
.br
.ti -1c
.RI "\fBpm_data\fP * \fBgui_pm_data_get\fP (\fBu_int8\fP id)"
.br
.ti -1c
.RI "GList * \fBgui_get_chat_users\fP (\fBu_int8\fP chat_id)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "static GtkListStore * \fBchat_model\fP"
.br
.ti -1c
.RI "static GtkTreeIter \fBchat_iter\fP"
.br
.ti -1c
.RI "static GHashTable * \fBtree_model_hashtable\fP = NULL"
.br
.ti -1c
.RI "static GHashTable * \fBpm_data_hashtable\fP = NULL"
.br
.ti -1c
.RI "GtkWidget * \fBbar_textfield\fP"
.br
.in -1c
.SH "Documentazione delle definizioni"
.PP 
.SS "#define AWAY   'Away'"
.PP
Definizione alla linea 37 del file gui.h.
.SS "#define BOTTOM   0x02"
.PP
Definizione alla linea 31 del file gui.h.
.SS "#define BUSY   'Busy'"
.PP
Definizione alla linea 36 del file gui.h.
.SS "#define CHAT   0x03"
.PP
Definizione alla linea 32 del file gui.h.
.SS "#define ONLINE   'Online'"
.PP
Definizione alla linea 35 del file gui.h.
.SS "#define PM   0x04"
.PP
Definizione alla linea 33 del file gui.h.
.SS "#define TOP   0x01"
.PP
Definizione alla linea 30 del file gui.h.
.SH "Documentazione delle ridefinizioni di tipo (typedef)"
.PP 
.SS "typedef struct \fBpm_data\fP \fBpm_data\fP"
.PP
Definizione alla linea 68 del file gui.h.
.SS "typedef struct \fBtree_model\fP \fBtree_model\fP"
.PP
Definizione alla linea 58 del file gui.h.
.SH "Documentazione delle funzioni"
.PP 
.SS "gint gui_add_chat (\fBu_int8\fP chat_id, char * chat_name)"
.PP
Definizione alla linea 71 del file gui.c.
.SS "gint gui_add_message (GtkTextView * widget, gchar * msg)"
.PP
Definizione alla linea 296 del file gui.c.
.SS "int gui_add_msg_pm (\fBu_int8\fP sender_id, char * msg)"
.PP
Definizione alla linea 578 del file gui.c.
.SS "int gui_add_msg_to_chat (\fBu_int8\fP chat_id, char * msg)"
.PP
Definizione alla linea 566 del file gui.c.
.SS "gint gui_add_user_to_chat (\fBu_int8\fP chat_id, \fBu_int8\fP id, char * user, \fBu_int1\fP status)"
.PP
Definizione alla linea 107 del file gui.c.
.SS "gint gui_change_status (\fBu_int8\fP user_id, char * status)"
.PP
Definizione alla linea 233 del file gui.c.
.SS "gint gui_clear_buffer (GtkTextView * widget)"
.PP
Definizione alla linea 284 del file gui.c.
.SS "gint gui_clear_chat_list ()"
.PP
Definizione alla linea 274 del file gui.c.
.SS "void gui_close_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 32 del file gui.c.
.SS "gint gui_close_window_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 22 del file gui.c.
.SS "gint gui_create_chat_button (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 457 del file gui.c.
.SS "GtkWidget* gui_create_chat_list (\fBu_int8\fP index)"
.PP
Definizione alla linea 671 del file gui.c.
.SS "GtkWidget* gui_create_menu (void)"
.PP
Definizione alla linea 708 del file gui.c.
.SS "GtkWidget* gui_create_searchbar (void)"
.PP
Definizione alla linea 985 del file gui.c.
.SS "GtkWidget* gui_create_text (\fBu_int8\fP chat_id, int type, int msg_type)"
.PP
Definizione alla linea 795 del file gui.c.
.SS "GtkWidget* gui_create_users_list (\fBu_int8\fP index)"
.PP
Definizione alla linea 616 del file gui.c.
.SS "gint gui_del_user_from_chat (\fBu_int8\fP chat_id, \fBu_int8\fP user_id)"
.PP
Definizione alla linea 195 del file gui.c.
.SS "GList* gui_get_chat_users (\fBu_int8\fP chat_id)"
.PP
Definizione alla linea 1026 del file gui.c.
.SS "\fBtree_model\fP* gui_get_tree_model (\fBu_int8\fP chat_id)"
.PP
Definizione alla linea 606 del file gui.c.
.SS "gint gui_leave_chat_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 44 del file gui.c.
.SS "gint gui_leave_pm_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 56 del file gui.c.
.SS "gint gui_open_about_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 388 del file gui.c.
.SS "void gui_open_chat_event (GtkTreeView * treeview, GtkTreePath * path, GtkTreeViewColumn * col, gpointer userdata)"
.PP
Definizione alla linea 329 del file gui.c.
.SS "int gui_open_chatroom (\fBu_int8\fP)"
.PP
Definizione alla linea 860 del file gui.c.
.SS "gint gui_open_conversation_event (GtkTreeView * treeview, GtkTreePath * path, GtkTreeViewColumn * col, gpointer userdata)"
.PP
Definizione alla linea 358 del file gui.c.
.SS "int gui_open_pm (\fBu_int8\fP user_id, gchar * nickname)"
.PP
Definizione alla linea 928 del file gui.c.
.SS "\fBpm_data\fP* gui_pm_data_get (\fBu_int8\fP id)"
.PP
Definizione alla linea 1015 del file gui.c.
.SS "gint gui_search_chat_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 445 del file gui.c.
.SS "gint gui_send_pm_message_event (GtkWidget * widget, GdkEventKey * event, gpointer gdata)"
.PP
Definizione alla linea 536 del file gui.c.
.SS "gint gui_send_text_message_event (GtkWidget * widget, GdkEventKey * event, gpointer gdata)"
.PP
Definizione alla linea 466 del file gui.c.
.SS "gint gui_set_to_away_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 433 del file gui.c.
.SS "gint gui_set_to_busy_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 422 del file gui.c.
.SS "gint gui_set_to_online_event (GtkWidget * widget, gpointer gdata)"
.PP
Definizione alla linea 411 del file gui.c.
.SH "Documentazione delle variabili"
.PP 
.SS "GtkWidget* \fBbar_textfield\fP"
.PP
Definizione alla linea 44 del file gui.h.
.SS "GtkTreeIter \fBchat_iter\fP\fC [static]\fP"
.PP
Definizione alla linea 40 del file gui.h.
.SS "GtkListStore* \fBchat_model\fP\fC [static]\fP"
.PP
Definizione alla linea 39 del file gui.h.
.SS "GHashTable* \fBpm_data_hashtable\fP = NULL\fC [static]\fP"
.PP
Definizione alla linea 42 del file gui.h.
.SS "GHashTable* \fBtree_model_hashtable\fP = NULL\fC [static]\fP"
.PP
Definizione alla linea 41 del file gui.h.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
