.TH "httpmanager.h" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httpmanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common.h'\fP
.br
\fC#include 'tortellaprotocol.h'\fP
.br
\fC#include 'socketmanager.h'\fP
.br
\fC#include 'utils.h'\fP
.br
\fC#include 'logger.h'\fP
.br

.SS "Strutture dati"

.in +1c
.ti -1c
.RI "struct \fBhttp_header_request\fP"
.br
.ti -1c
.RI "struct \fBhttp_header_response\fP"
.br
.ti -1c
.RI "struct \fBhttp_packet\fP"
.br
.in -1c
.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBHTTP_REQ_GET\fP   0x40"
.br
.ti -1c
.RI "#define \fBHTTP_RES_GET\fP   0x41"
.br
.ti -1c
.RI "#define \fBHTTP_REQ_POST\fP   0x42"
.br
.ti -1c
.RI "#define \fBHTTP_RES_POST\fP   0x43"
.br
.ti -1c
.RI "#define \fBHTTP_STATUS_OK\fP   200"
.br
.ti -1c
.RI "#define \fBHTTP_STATUS_CERROR\fP   400"
.br
.ti -1c
.RI "#define \fBHTTP_STATUS_SERROR\fP   500"
.br
.ti -1c
.RI "#define \fBHTTP_REQ_POST_LINE\fP   'POST * HTTP/1.1'"
.br
.ti -1c
.RI "#define \fBHTTP_AGENT\fP   'User-Agent: '"
.br
.ti -1c
.RI "#define \fBHTTP_REQ_RANGE\fP   'Range: bytes='"
.br
.ti -1c
.RI "#define \fBHTTP_CONNECTION\fP   'Connection: '"
.br
.ti -1c
.RI "#define \fBHTTP_CONTENT_TYPE\fP   'Content-Type: '"
.br
.ti -1c
.RI "#define \fBHTTP_CONTENT_LEN\fP   'Content-Length: '"
.br
.ti -1c
.RI "#define \fBHTTP_SERVER\fP   'Server: '"
.br
.ti -1c
.RI "#define \fBHTTP_OK\fP   'HTTP/1.1 200 OK'"
.br
.ti -1c
.RI "#define \fBHTTP_CERROR\fP   'HTTP/1.1 400 Bad Request'"
.br
.ti -1c
.RI "#define \fBHTTP_SERROR\fP   'HTTP/1.1 500 Internal Server Error'"
.br
.in -1c
.SS "Ridefinizioni di tipo (typedef)"

.in +1c
.ti -1c
.RI "typedef struct \fBhttp_header_request\fP \fBhttp_header_request\fP"
.br
.ti -1c
.RI "typedef struct \fBhttp_header_response\fP \fBhttp_header_response\fP"
.br
.ti -1c
.RI "typedef struct \fBhttp_packet\fP \fBhttp_packet\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "\fBhttp_packet\fP * \fBhttp_create_packet\fP (\fBtortella_packet\fP *packet, \fBu_int4\fP type, \fBu_int4\fP status, char *filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, char *data, \fBu_int4\fP data_len)"
.br
.ti -1c
.RI "\fBhttp_header_request\fP * \fBhttp_create_header_request\fP (\fBhttp_header_request\fP *header, \fBu_int4\fP type, char *filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, \fBu_int4\fP data_len)"
.br
.ti -1c
.RI "\fBhttp_header_response\fP * \fBhttp_create_header_response\fP (\fBhttp_header_response\fP *header, \fBu_int4\fP type, \fBu_int4\fP status, \fBu_int4\fP content_len)"
.br
.ti -1c
.RI "char * \fBhttp_bin_to_char\fP (\fBhttp_packet\fP *packet, int *len)"
.br
.ti -1c
.RI "\fBhttp_packet\fP * \fBhttp_char_to_bin\fP (const char *buffer)"
.br
.ti -1c
.RI "char * \fBhttp_get_value\fP (const char *buffer, const char *name)"
.br
.ti -1c
.RI "char * \fBhttp_get_line\fP (const char *buffer, \fBu_int4\fP num)"
.br
.in -1c
.SH "Documentazione delle definizioni"
.PP 
.SS "#define HTTP_AGENT   'User-Agent: '"
.PP
Definizione alla linea 35 del file httpmanager.h.
.SS "#define HTTP_CERROR   'HTTP/1.1 400 Bad Request'"
.PP
Definizione alla linea 43 del file httpmanager.h.
.SS "#define HTTP_CONNECTION   'Connection: '"
.PP
Definizione alla linea 37 del file httpmanager.h.
.SS "#define HTTP_CONTENT_LEN   'Content-Length: '"
.PP
Definizione alla linea 39 del file httpmanager.h.
.SS "#define HTTP_CONTENT_TYPE   'Content-Type: '"
.PP
Definizione alla linea 38 del file httpmanager.h.
.SS "#define HTTP_OK   'HTTP/1.1 200 OK'"
.PP
Definizione alla linea 42 del file httpmanager.h.
.SS "#define HTTP_REQ_GET   0x40"
.PP
Definizione alla linea 26 del file httpmanager.h.
.SS "#define HTTP_REQ_POST   0x42"
.PP
Definizione alla linea 28 del file httpmanager.h.
.SS "#define HTTP_REQ_POST_LINE   'POST * HTTP/1.1'"
.PP
Definizione alla linea 34 del file httpmanager.h.
.SS "#define HTTP_REQ_RANGE   'Range: bytes='"
.PP
Definizione alla linea 36 del file httpmanager.h.
.SS "#define HTTP_RES_GET   0x41"
.PP
Definizione alla linea 27 del file httpmanager.h.
.SS "#define HTTP_RES_POST   0x43"
.PP
Definizione alla linea 29 del file httpmanager.h.
.SS "#define HTTP_SERROR   'HTTP/1.1 500 Internal Server Error'"
.PP
Definizione alla linea 44 del file httpmanager.h.
.SS "#define HTTP_SERVER   'Server: '"
.PP
Definizione alla linea 40 del file httpmanager.h.
.SS "#define HTTP_STATUS_CERROR   400"
.PP
Definizione alla linea 31 del file httpmanager.h.
.SS "#define HTTP_STATUS_OK   200"
.PP
Definizione alla linea 30 del file httpmanager.h.
.SS "#define HTTP_STATUS_SERROR   500"
.PP
Definizione alla linea 32 del file httpmanager.h.
.SH "Documentazione delle ridefinizioni di tipo (typedef)"
.PP 
.SS "typedef struct \fBhttp_header_request\fP \fBhttp_header_request\fP"
.PP
Definizione alla linea 55 del file httpmanager.h.
.SS "typedef struct \fBhttp_header_response\fP \fBhttp_header_response\fP"
.PP
Definizione alla linea 64 del file httpmanager.h.
.SS "typedef struct \fBhttp_packet\fP \fBhttp_packet\fP"
.PP
Definizione alla linea 78 del file httpmanager.h.
.SH "Documentazione delle funzioni"
.PP 
.SS "char* http_bin_to_char (\fBhttp_packet\fP * packet, int * len)"
.PP
Definizione alla linea 164 del file httpmanager.c.
.SS "\fBhttp_packet\fP* http_char_to_bin (const char * buffer)"
.PP
Definizione alla linea 259 del file httpmanager.c.
.SS "\fBhttp_header_request\fP* http_create_header_request (\fBhttp_header_request\fP * header, \fBu_int4\fP type, char * filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, \fBu_int4\fP data_len)"
.PP
Definizione alla linea 112 del file httpmanager.c.
.SS "\fBhttp_header_response\fP* http_create_header_response (\fBhttp_header_response\fP * header, \fBu_int4\fP type, \fBu_int4\fP status, \fBu_int4\fP content_len)"
.PP
Definizione alla linea 137 del file httpmanager.c.
.SS "\fBhttp_packet\fP* http_create_packet (\fBtortella_packet\fP * packet, \fBu_int4\fP type, \fBu_int4\fP status, char * filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, char * data, \fBu_int4\fP data_len)"
.PP
Definizione alla linea 55 del file httpmanager.c.
.SS "char* http_get_line (const char * buffer, \fBu_int4\fP num)"
.PP
Definizione alla linea 377 del file httpmanager.c.
.SS "char* http_get_value (const char * buffer, const char * name)"
.PP
Definizione alla linea 356 del file httpmanager.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
