.TH "http_packet" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_packet \- 
.SH SYNOPSIS
.br
.PP
\fC#include <httpmanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int4\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBhttp_header_request\fP * \fBheader_request\fP"
.br
.ti -1c
.RI "\fBhttp_header_response\fP * \fBheader_response\fP"
.br
.ti -1c
.RI "\fBtortella_packet\fP * \fBdata\fP"
.br
.ti -1c
.RI "char * \fBdata_string\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBdata_len\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 70 del file httpmanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int4\fP \fBhttp_packet::type\fP"
.PP
Definizione alla linea 71 del file httpmanager.h.
.SS "\fBhttp_header_request\fP* \fBhttp_packet::header_request\fP"
.PP
Definizione alla linea 72 del file httpmanager.h.
.SS "\fBhttp_header_response\fP* \fBhttp_packet::header_response\fP"
.PP
Definizione alla linea 73 del file httpmanager.h.
.SS "\fBtortella_packet\fP* \fBhttp_packet::data\fP"
.PP
Definizione alla linea 74 del file httpmanager.h.
.SS "char* \fBhttp_packet::data_string\fP"
.PP
Definizione alla linea 75 del file httpmanager.h.
.SS "\fBu_int4\fP \fBhttp_packet::data_len\fP"
.PP
Definizione alla linea 76 del file httpmanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
