.TH "init_data" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init_data \- dati dei peer inizialmente conosciuti.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <init.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBport\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
dati dei peer inizialmente conosciuti. 


.PP
Definizione alla linea 33 del file init.h.
.SH "Documentazione dei campi"
.PP 
.SS "char* \fBinit_data::ip\fP"
.PP
Definizione alla linea 34 del file init.h.
.SS "\fBu_int4\fP \fBinit_data::port\fP"
.PP
Definizione alla linea 35 del file init.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
