.TH "testing/init_testing.c" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/init_testing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'init.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definizione alla linea 19 del file init_testing.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
