.TH "leave_desc" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leave_desc \- struttura dati per l'invio del pacchetto LEAVE ad una \fBchat\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBuser_id\fP"
.br
.ti -1c
.RI "\fBu_int8\fP \fBchat_id\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBhops\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struttura dati per l'invio del pacchetto LEAVE ad una \fBchat\fP. 

I dati salvati sono rispettivamente l'ID dell'utente che vuole uscire dalla \fBchat\fP e il rispettivo identificativo della \fBchat\fP. Come per il pacchetto JOIN anche in questo caso i dati memorizzati rimarranno identici(a meno del TTL e HOPS) per tutto il percorso fatto nella rete. 
.PP
Definizione alla linea 130 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBleave_desc::user_id\fP"
.PP
Definizione alla linea 131 del file tortellaprotocol.h.
.SS "\fBu_int8\fP \fBleave_desc::chat_id\fP"
.PP
Definizione alla linea 132 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBleave_desc::ttl\fP"
.PP
Definizione alla linea 133 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBleave_desc::hops\fP"
.PP
Definizione alla linea 134 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
