.TH "pm_data" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pm_data \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gui.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "GtkWidget * \fBwindow\fP"
.br
.ti -1c
.RI "GtkTextView * \fBtext_area\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 64 del file gui.h.
.SH "Documentazione dei campi"
.PP 
.SS "GtkWidget* \fBpm_data::window\fP"
.PP
Definizione alla linea 65 del file gui.h.
.SS "GtkTextView* \fBpm_data::text_area\fP"
.PP
Definizione alla linea 66 del file gui.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
