.TH "routemanager.h" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
routemanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common.h'\fP
.br
\fC#include 'packetmanager.h'\fP
.br
\fC#include 'utils.h'\fP
.br
\fC#include 'datamanager.h'\fP
.br
\fC#include 'init.h'\fP
.br
\fC#include 'routemanager.h'\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <glib.h>\fP
.br

.SS "Strutture dati"

.in +1c
.ti -1c
.RI "struct \fBroute_entry\fP"
.br
.in -1c
.SS "Ridefinizioni di tipo (typedef)"

.in +1c
.ti -1c
.RI "typedef struct \fBroute_entry\fP \fBroute_entry\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBadd_route_entry\fP (\fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id)"
.br
.ti -1c
.RI "int \fBdel_route_entry\fP (\fBu_int8\fP id)"
.br
.ti -1c
.RI "\fBroute_entry\fP * \fBget_route_entry\fP (\fBu_int8\fP packet_id)"
.br
.ti -1c
.RI "\fBu_int8\fP \fBget_iddest_route_entry\fP (\fBu_int8\fP id)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "static GHashTable * \fBroute_hashtable\fP = NULL"
.br
.in -1c
.SH "Documentazione delle ridefinizioni di tipo (typedef)"
.PP 
.SS "typedef struct \fBroute_entry\fP \fBroute_entry\fP"
.PP
Definizione alla linea 36 del file routemanager.h.
.SH "Documentazione delle funzioni"
.PP 
.SS "int add_route_entry (\fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id)"
.PP
Definizione alla linea 24 del file routemanager.c.
.SS "int del_route_entry (\fBu_int8\fP id)"
.PP
Definizione alla linea 48 del file routemanager.c.
.SS "\fBu_int8\fP get_iddest_route_entry (\fBu_int8\fP id)"
.PP
Definizione alla linea 81 del file routemanager.c.
.SS "\fBroute_entry\fP* get_route_entry (\fBu_int8\fP packet_id)"
.PP
Definizione alla linea 68 del file routemanager.c.
.SH "Documentazione delle variabili"
.PP 
.SS "GHashTable* \fBroute_hashtable\fP = NULL\fC [static]\fP"
.PP
Definizione alla linea 38 del file routemanager.h.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
