.TH "searchhits_desc" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searchhits_desc \- struct per l'invio del pacchetto SEARCHHITS.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int4\fP \fBnum_res\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struct per l'invio del pacchetto SEARCHHITS. 

Il routing di tale pacchetto segue il percorso inverso di quello eseguito dal pacchetto SEARCH. 
.PP
Definizione alla linea 181 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int4\fP \fBsearchhits_desc::num_res\fP"
.PP
Definizione alla linea 182 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
