.TH "testing/SocketTest.c" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/SocketTest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'SocketManager.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBtestSocket\fP ()"
.br
.ti -1c
.RI "void \fBtestListenSocket\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definizione alla linea 11 del file SocketTest.c.
.SS "void testListenSocket ()"
.PP
Definizione alla linea 36 del file SocketTest.c.
.SS "void testSocket ()"
.PP
Definizione alla linea 22 del file SocketTest.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
