.TH "bye_desc" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bye_desc \- struttura usata per segnalare la disconnessione dalla rete tortella.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SH "Descrizione dettagliata"
.PP 
struttura usata per segnalare la disconnessione dalla rete tortella. 
.PP
Definizione alla linea 190 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
