.TH "controller.h" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'servent.h'\fP
.br
\fC#include 'common.h'\fP
.br
\fC#include 'socketmanager.h'\fP
.br
\fC#include 'datamanager.h'\fP
.br
\fC#include 'confmanager.h'\fP
.br
\fC#include <glib.h>\fP
.br
\fC#include 'gui.h'\fP
.br
\fC#include 'utils.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBcontroller_change_status\fP (\fBu_int1\fP status)"
.br
.ti -1c
.RI "int \fBcontroller_manipulating_status\fP (\fBu_int8\fP user_id, \fBu_int1\fP status)"
.br
.ti -1c
.RI "int \fBcontroller_send_chat_users\fP (\fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char *msg)"
.br
.ti -1c
.RI "int \fBcontroller_send_subset_users\fP (\fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char *msg, GList *users)"
.br
.ti -1c
.RI "int \fBcontroller_send_pm\fP (\fBu_int4\fP msg_len, char *msg, \fBu_int8\fP recv_id)"
.br
.ti -1c
.RI "int \fBcontroller_leave_all_chat\fP ()"
.br
.ti -1c
.RI "int \fBcontroller_connect_users\fP (GList *users)"
.br
.ti -1c
.RI "int \fBcontroller_check_users_con\fP (GList *users)"
.br
.ti -1c
.RI "int \fBcontroller_send_bye\fP ()"
.br
.ti -1c
.RI "int \fBcontroller_receive_bye\fP ()"
.br
.ti -1c
.RI "int \fBcontroller_init\fP (const char *filename, const char *cache)"
.br
.ti -1c
.RI "int \fBcontroller_exit\fP ()"
.br
.ti -1c
.RI "int \fBcontroller_init_gui\fP (void)"
.br
.ti -1c
.RI "\fBu_int8\fP \fBcontroller_search\fP (const char *query)"
.br
.ti -1c
.RI "int \fBcontroller_join_flooding\fP (\fBu_int8\fP chat_id)"
.br
.ti -1c
.RI "int \fBcontroller_leave_flooding\fP (\fBu_int8\fP chat_id)"
.br
.ti -1c
.RI "int \fBcontroller_create\fP (const char *title)"
.br
.ti -1c
.RI "int \fBcontroller_add_user_to_chat\fP (\fBu_int8\fP chat_id, \fBu_int8\fP id)"
.br
.ti -1c
.RI "int \fBcontroller_rem_user_from_chat\fP (\fBu_int8\fP chat_id, \fBu_int8\fP id)"
.br
.ti -1c
.RI "int \fBcontroller_add_msg_to_chat\fP (\fBu_int8\fP chat_id, char *msg)"
.br
.ti -1c
.RI "int \fBcontroller_add_msg\fP (\fBu_int8\fP sender_id, char *msg)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "pthread_t \fBgtk_main_thread\fP"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int controller_add_msg (\fBu_int8\fP sender_id, char * msg)"
.PP
Definizione alla linea 829 del file controller.c.
.SS "int controller_add_msg_to_chat (\fBu_int8\fP chat_id, char * msg)"
.PP
Definizione alla linea 807 del file controller.c.
.SS "int controller_add_user_to_chat (\fBu_int8\fP chat_id, \fBu_int8\fP id)"
.PP
Definizione alla linea 776 del file controller.c.
.SS "int controller_change_status (\fBu_int1\fP status)"
.PP
Definizione alla linea 23 del file controller.c.
.SS "int controller_check_users_con (GList * users)"
.PP
Definizione alla linea 321 del file controller.c.
.SS "int controller_connect_users (GList * users)"
.PP
Definizione alla linea 249 del file controller.c.
.SS "int controller_create (const char * title)"
.PP
Definizione alla linea 746 del file controller.c.
.SS "int controller_exit ()"
.PP
Definizione alla linea 452 del file controller.c.
.SS "int controller_init (const char * filename, const char * cache)"
.PP
Definizione alla linea 428 del file controller.c.
.SS "int controller_init_gui (void)"
.PP
Definizione alla linea 463 del file controller.c.
.SS "int controller_join_flooding (\fBu_int8\fP chat_id)"
.PP
Definizione alla linea 581 del file controller.c.
.SS "int controller_leave_all_chat ()"
.PP
Definizione alla linea 224 del file controller.c.
.SS "int controller_leave_flooding (\fBu_int8\fP chat_id)"
.PP
Definizione alla linea 680 del file controller.c.
.SS "int controller_manipulating_status (\fBu_int8\fP user_id, \fBu_int1\fP status)"
.PP
Definizione alla linea 64 del file controller.c.
.SS "int controller_receive_bye ()"
.PP
.SS "int controller_rem_user_from_chat (\fBu_int8\fP chat_id, \fBu_int8\fP id)"
.PP
Definizione alla linea 797 del file controller.c.
.SS "\fBu_int8\fP controller_search (const char * query)"
.PP
Definizione alla linea 522 del file controller.c.
.SS "int controller_send_bye ()"
.PP
Definizione alla linea 353 del file controller.c.
.SS "int controller_send_chat_users (\fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char * msg)"
.PP
Definizione alla linea 84 del file controller.c.
.SS "int controller_send_pm (\fBu_int4\fP msg_len, char * msg, \fBu_int8\fP recv_id)"
.PP
Definizione alla linea 192 del file controller.c.
.SS "int controller_send_subset_users (\fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char * msg, GList * users)"
.PP
Definizione alla linea 145 del file controller.c.
.SH "Documentazione delle variabili"
.PP 
.SS "pthread_t \fBgtk_main_thread\fP"
.PP
Definizione alla linea 29 del file controller.h.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
