.TH "httpmanager.c" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httpmanager.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'httpmanager.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "\fBhttp_packet\fP * \fBhttp_create_packet\fP (\fBtortella_packet\fP *packet, \fBu_int4\fP type, \fBu_int4\fP status, char *filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, char *data, \fBu_int4\fP data_len)"
.br
.ti -1c
.RI "\fBhttp_header_request\fP * \fBhttp_create_header_request\fP (\fBhttp_header_request\fP *header, \fBu_int4\fP type, char *filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, \fBu_int4\fP data_len)"
.br
.ti -1c
.RI "\fBhttp_header_response\fP * \fBhttp_create_header_response\fP (\fBhttp_header_response\fP *header, \fBu_int4\fP type, \fBu_int4\fP status, \fBu_int4\fP content_len)"
.br
.ti -1c
.RI "char * \fBhttp_bin_to_char\fP (\fBhttp_packet\fP *packet, int *len)"
.br
.ti -1c
.RI "\fBhttp_packet\fP * \fBhttp_char_to_bin\fP (const char *buffer)"
.br
.ti -1c
.RI "char * \fBhttp_get_value\fP (const char *buffer, const char *name)"
.br
.ti -1c
.RI "char * \fBhttp_get_line\fP (const char *buffer, \fBu_int4\fP num)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "char* http_bin_to_char (\fBhttp_packet\fP * packet, int * len)"
.PP
Definizione alla linea 164 del file httpmanager.c.
.SS "\fBhttp_packet\fP* http_char_to_bin (const char * buffer)"
.PP
Definizione alla linea 259 del file httpmanager.c.
.SS "\fBhttp_header_request\fP* http_create_header_request (\fBhttp_header_request\fP * header, \fBu_int4\fP type, char * filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, \fBu_int4\fP data_len)"
.PP
Definizione alla linea 112 del file httpmanager.c.
.SS "\fBhttp_header_response\fP* http_create_header_response (\fBhttp_header_response\fP * header, \fBu_int4\fP type, \fBu_int4\fP status, \fBu_int4\fP content_len)"
.PP
Definizione alla linea 137 del file httpmanager.c.
.SS "\fBhttp_packet\fP* http_create_packet (\fBtortella_packet\fP * packet, \fBu_int4\fP type, \fBu_int4\fP status, char * filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end, char * data, \fBu_int4\fP data_len)"
.PP
Definizione alla linea 55 del file httpmanager.c.
.SS "char* http_get_line (const char * buffer, \fBu_int4\fP num)"
.PP
Definizione alla linea 377 del file httpmanager.c.
.SS "char* http_get_value (const char * buffer, const char * name)"
.PP
Definizione alla linea 356 del file httpmanager.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
