.TH "packetmanager.h" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packetmanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common.h'\fP
.br
\fC#include 'tortellaprotocol.h'\fP
.br
\fC#include 'httpmanager.h'\fP
.br
\fC#include 'socketmanager.h'\fP
.br
\fC#include 'utils.h'\fP
.br
\fC#include 'logger.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBsend_search_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP ttl, \fBu_int1\fP hops, \fBu_int4\fP string_len, char *string)"
.br
.RI "\fIinvio di un pacchetto http contenente una search \fP"
.ti -1c
.RI "int \fBsend_searchhits_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int4\fP num_res, \fBu_int4\fP res_len, char *res)"
.br
.RI "\fIinvio di un pacchetto http contenente una searchhits \fP"
.ti -1c
.RI "int \fBsend_join_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP status, \fBu_int8\fP user_id, \fBu_int8\fP chat_id, char *\fBnick\fP, \fBu_int4\fP port, char *ip, \fBu_int1\fP ttl, \fBu_int1\fP hops)"
.br
.RI "\fIinvio di un pacchetto http contenente una join \fP"
.ti -1c
.RI "int \fBsend_leave_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int8\fP user_id, \fBu_int8\fP chat_id, \fBu_int1\fP ttl, \fBu_int1\fP hops)"
.br
.RI "\fIinvio di un pacchetto http contenente una leave \fP"
.ti -1c
.RI "int \fBsend_ping_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, char *\fBnick\fP, \fBu_int4\fP port, \fBu_int1\fP status)"
.br
.RI "\fIinvio di un pacchetto http contenente un ping \fP"
.ti -1c
.RI "int \fBsend_list_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP ttl, \fBu_int1\fP hops, \fBu_int8\fP chat_id)"
.br
.RI "\fIinvio di un pacchetto http contenente una list. \fP"
.ti -1c
.RI "int \fBsend_listhits_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int4\fP user_num, \fBu_int4\fP res_len, char *res, \fBu_int8\fP chat_id)"
.br
.RI "\fIinvio di un pacchetto http contenente una listhits. \fP"
.ti -1c
.RI "int \fBsend_bye_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id)"
.br
.RI "\fIinvio di un pacchetto http contenente una bye \fP"
.ti -1c
.RI "int \fBsend_message_packet\fP (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char *msg)"
.br
.RI "\fIinvio di un pacchetto http contenente un messaggio \fP"
.ti -1c
.RI "int \fBsend_post_response_packet\fP (\fBu_int4\fP fd, \fBu_int4\fP status, \fBu_int4\fP data_len, char *data)"
.br
.RI "\fIinvio di un pacchetto http di risposta al POST \fP"
.ti -1c
.RI "int \fBsend_get_request_packet\fP (\fBu_int4\fP fd, char *filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end)"
.br
.RI "\fIinvio di un pacchetto http di tipo GET \fP"
.ti -1c
.RI "int \fBsend_get_response_packet\fP (\fBu_int4\fP fd, \fBu_int4\fP status, \fBu_int4\fP data_len, char *data)"
.br
.RI "\fIinvio di un pacchetto http di risposta \fP"
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int send_bye_packet (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id)"
.PP
invio di un pacchetto http contenente una bye 
.PP
Definizione alla linea 287 del file packetmanager.c.
.SS "int send_get_request_packet (\fBu_int4\fP fd, char * filename, \fBu_int4\fP range_start, \fBu_int4\fP range_end)"
.PP
invio di un pacchetto http di tipo GET 
.PP
Definizione alla linea 384 del file packetmanager.c.
.SS "int send_get_response_packet (\fBu_int4\fP fd, \fBu_int4\fP status, \fBu_int4\fP data_len, char * data)"
.PP
invio di un pacchetto http di risposta 
.PP
Definizione alla linea 398 del file packetmanager.c.
.SS "int send_join_packet (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP status, \fBu_int8\fP user_id, \fBu_int8\fP chat_id, char * nick, \fBu_int4\fP port, char * ip, \fBu_int1\fP ttl, \fBu_int1\fP hops)"
.PP
invio di un pacchetto http contenente una join 
.PP
Definizione alla linea 93 del file packetmanager.c.
.SS "int send_leave_packet (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int8\fP user_id, \fBu_int8\fP chat_id, \fBu_int1\fP ttl, \fBu_int1\fP hops)"
.PP
invio di un pacchetto http contenente una leave 
.PP
Definizione alla linea 136 del file packetmanager.c.
.SS "int send_list_packet (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP ttl, \fBu_int1\fP hops, \fBu_int8\fP chat_id)"
.PP
invio di un pacchetto http contenente una list. 
.PP
Non utilizzato 
.PP
Definizione alla linea 212 del file packetmanager.c.
.SS "int send_listhits_packet (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int4\fP user_num, \fBu_int4\fP res_len, char * res, \fBu_int8\fP chat_id)"
.PP
invio di un pacchetto http contenente una listhits. 
.PP
Non utilizzato 
.PP
Definizione alla linea 250 del file packetmanager.c.
.SS "int send_message_packet (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int8\fP chat_id, \fBu_int4\fP msg_len, char * msg)"
.PP
invio di un pacchetto http contenente un messaggio 
.PP
Definizione alla linea 322 del file packetmanager.c.
.SS "int send_ping_packet (\fBu_int4\fP fd, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, char * nick, \fBu_int4\fP port, \fBu_int1\fP status)"
.PP
invio di un pacchetto http contenente un ping 
.PP
Definizione alla linea 175 del file packetmanager.c.
.SS "int send_post_response_packet (\fBu_int4\fP fd, \fBu_int4\fP status, \fBu_int4\fP data_len, char * data)"
.PP
invio di un pacchetto http di risposta al POST 
.PP
Definizione alla linea 360 del file packetmanager.c.
.SS "int send_search_packet (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int1\fP ttl, \fBu_int1\fP hops, \fBu_int4\fP string_len, char * string)"
.PP
invio di un pacchetto http contenente una search 
.PP
Definizione alla linea 20 del file packetmanager.c.
.SS "int send_searchhits_packet (\fBu_int4\fP fd, \fBu_int8\fP packet_id, \fBu_int8\fP sender_id, \fBu_int8\fP recv_id, \fBu_int4\fP num_res, \fBu_int4\fP res_len, char * res)"
.PP
invio di un pacchetto http contenente una searchhits 
.PP
Definizione alla linea 57 del file packetmanager.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
