.TH "route_entry" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
route_entry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <routemanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBsender_id\fP"
.br
.ti -1c
.RI "\fBu_int8\fP \fBrecv_id\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBcounter\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 31 del file routemanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBroute_entry::sender_id\fP"
.PP
Definizione alla linea 32 del file routemanager.h.
.SS "\fBu_int8\fP \fBroute_entry::recv_id\fP"
.PP
Definizione alla linea 33 del file routemanager.h.
.SS "\fBu_int4\fP \fBroute_entry::counter\fP"
.PP
Definizione alla linea 34 del file routemanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
