.TH "search_desc" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search_desc \- struct per il flooding del pacchetto SEARCH.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int1\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBhops\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struct per il flooding del pacchetto SEARCH. 

Ogni utente invierà una richiesta di ricerca, e in tale struttura verrà decrementato il valore del TTL e incrementato quello dell'HOPS per ogni nodo attraversato dal pacchetto durante il suo percorso nella rete. 
.PP
Definizione alla linea 167 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int1\fP \fBsearch_desc::ttl\fP"
.PP
Definizione alla linea 168 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBsearch_desc::hops\fP"
.PP
Definizione alla linea 169 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
