.TH "tree_model" 3 "17 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree_model \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gui.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "GtkListStore * \fBuser_model\fP"
.br
.ti -1c
.RI "GtkTreeIter \fBuser_iter\fP"
.br
.ti -1c
.RI "GtkTextView * \fBtext_area\fP"
.br
.ti -1c
.RI "GtkTreeView * \fBtree_view\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 51 del file gui.h.
.SH "Documentazione dei campi"
.PP 
.SS "GtkListStore* \fBtree_model::user_model\fP"
.PP
Definizione alla linea 53 del file gui.h.
.SS "GtkTreeIter \fBtree_model::user_iter\fP"
.PP
Definizione alla linea 54 del file gui.h.
.SS "GtkTextView* \fBtree_model::text_area\fP"
.PP
Definizione alla linea 55 del file gui.h.
.SS "GtkTreeView* \fBtree_model::tree_view\fP"
.PP
Definizione alla linea 56 del file gui.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
