.TH "chatclient" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chatclient \- utente connesso ad una \fBchat\fP  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <datamanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBid\fP"
.br
.ti -1c
.RI "char * \fBnick\fP"
.br
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBport\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
utente connesso ad una \fBchat\fP 
.PP
Definizione alla linea 37 del file datamanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBchatclient::id\fP"
.PP
Definizione alla linea 38 del file datamanager.h.
.SS "char* \fBchatclient::nick\fP"
.PP
Definizione alla linea 39 del file datamanager.h.
.SS "char* \fBchatclient::ip\fP"
.PP
Definizione alla linea 40 del file datamanager.h.
.SS "\fBu_int4\fP \fBchatclient::port\fP"
.PP
Definizione alla linea 41 del file datamanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
