.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/common.h" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/common.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Ridefinizioni di tipo (typedef)"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBu_int1\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBu_int2\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBu_int4\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBu_int8\fP"
.br
.in -1c
.SH "Documentazione delle ridefinizioni di tipo (typedef)"
.PP 
.SS "typedef unsigned char \fBu_int1\fP"
.PP
Definizione alla linea 20 del file common.h.
.SS "typedef unsigned short \fBu_int2\fP"
.PP
Definizione alla linea 21 del file common.h.
.SS "typedef unsigned int \fBu_int4\fP"
.PP
Definizione alla linea 22 del file common.h.
.SS "typedef unsigned long long \fBu_int8\fP"
.PP
Definizione alla linea 23 del file common.h.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
