.TH "http_header_response" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_header_response \- header della response http  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <httpmanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "char * \fBresponse\fP"
.br
.ti -1c
.RI "char * \fBserver\fP"
.br
.ti -1c
.RI "char * \fBcontent_type\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBcontent_len\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
header della response http 
.PP
Definizione alla linea 58 del file httpmanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "char* \fBhttp_header_response::response\fP"
.PP
Definizione alla linea 59 del file httpmanager.h.
.SS "char* \fBhttp_header_response::server\fP"
.PP
Definizione alla linea 60 del file httpmanager.h.
.SS "char* \fBhttp_header_response::content_type\fP"
.PP
Definizione alla linea 61 del file httpmanager.h.
.SS "\fBu_int4\fP \fBhttp_header_response::content_len\fP"
.PP
Definizione alla linea 62 del file httpmanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
