.TH "list_desc" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_desc \- struttura dati per il pacchetto LIST, in cui viene memorizzato il valore del TTL e dell' HOPS, e l'ID della \fBchat\fP di cui si richiede la lista degli utenti presenti  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBchat_id\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBhops\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struttura dati per il pacchetto LIST, in cui viene memorizzato il valore del TTL e dell' HOPS, e l'ID della \fBchat\fP di cui si richiede la lista degli utenti presenti 
.PP
Definizione alla linea 93 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBlist_desc::chat_id\fP"
.PP
Definizione alla linea 94 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBlist_desc::ttl\fP"
.PP
Definizione alla linea 95 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBlist_desc::hops\fP"
.PP
Definizione alla linea 96 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
