.TH "route_entry" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
route_entry \- This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <routemanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBsender_id\fP"
.br
.ti -1c
.RI "\fBu_int8\fP \fBrecv_id\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBcounter\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301, USA 
.PP
Definizione alla linea 31 del file routemanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBroute_entry::sender_id\fP"
.PP
Definizione alla linea 32 del file routemanager.h.
.SS "\fBu_int8\fP \fBroute_entry::recv_id\fP"
.PP
Definizione alla linea 33 del file routemanager.h.
.SS "\fBu_int4\fP \fBroute_entry::counter\fP"
.PP
Definizione alla linea 34 del file routemanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
