.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/tortella.c" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/tortella.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controller.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "\fIThis program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. \fP"
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301, USA Lancia l'applicazione, inizializzando il controller in due modalita' differenti a seconda dei parametri passati da riga di comando. Il primo parametro dev'essere il path del file di configurazione, mentre il secondo (opzionale nel caso non si conosca alcun vicino) dev'essere il path del file in cui sono inseriti ip e porta dei peer vicini conosciuti. La seconda fase consiste nell'inizializzazione dei thread necessari a gestire la gui e infine si avvia l'interfaccia grafica tramite la chiamata a \fBcontroller_init_gui()\fP. 
.PP
inizializzazione del controller
.PP
inizializzazione dei thread
.PP
inizializzazione della gui 
.PP
Definizione alla linea 28 del file tortella.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
