.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/testing/tortellaprotocol_testing.c" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/testing/tortellaprotocol_testing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tortellaprotocol.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definizione alla linea 21 del file tortellaprotocol_testing.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
