.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/confmanager.c" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/confmanager.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'confmanager.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBconf_read\fP (const char *filename)"
.br
.ti -1c
.RI "int \fBconf_save_value\fP (const char *line)"
.br
.ti -1c
.RI "int \fBconf_get_qlen\fP (void)"
.br
.ti -1c
.RI "int \fBconf_get_buffer_len\fP (void)"
.br
.ti -1c
.RI "char * \fBconf_get_path\fP (void)"
.br
.ti -1c
.RI "\fBu_int8\fP \fBconf_get_gen_start\fP (void)"
.br
.ti -1c
.RI "char * \fBconf_get_datadir\fP (void)"
.br
.ti -1c
.RI "char * \fBconf_get_local_ip\fP (void)"
.br
.ti -1c
.RI "\fBu_int4\fP \fBconf_get_local_port\fP (void)"
.br
.ti -1c
.RI "char * \fBconf_get_nick\fP (void)"
.br
.ti -1c
.RI "int \fBconf_get_verbose\fP (void)"
.br
.ti -1c
.RI "\fBu_int4\fP \fBconf_get_timer_interval\fP (void)"
.br
.ti -1c
.RI "\fBu_int8\fP \fBconf_get_connection_id_limit\fP (void)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int conf_get_buffer_len (void)"
.PP
Definizione alla linea 100 del file confmanager.c.
.SS "\fBu_int8\fP conf_get_connection_id_limit (void)"
.PP
Definizione alla linea 136 del file confmanager.c.
.SS "char* conf_get_datadir (void)"
.PP
Definizione alla linea 112 del file confmanager.c.
.SS "\fBu_int8\fP conf_get_gen_start (void)"
.PP
Definizione alla linea 108 del file confmanager.c.
.SS "char* conf_get_local_ip (void)"
.PP
Definizione alla linea 116 del file confmanager.c.
.SS "\fBu_int4\fP conf_get_local_port (void)"
.PP
Definizione alla linea 120 del file confmanager.c.
.SS "char* conf_get_nick (void)"
.PP
Definizione alla linea 124 del file confmanager.c.
.SS "char* conf_get_path (void)"
.PP
Definizione alla linea 104 del file confmanager.c.
.SS "int conf_get_qlen (void)"
.PP
Definizione alla linea 96 del file confmanager.c.
.SS "\fBu_int4\fP conf_get_timer_interval (void)"
.PP
Definizione alla linea 132 del file confmanager.c.
.SS "int conf_get_verbose (void)"
.PP
Definizione alla linea 128 del file confmanager.c.
.SS "int conf_read (const char * filename)"
.PP

.PP
printf('Comment\\n');
.PP
printf('Empty line\\n'); 
.PP
Definizione alla linea 3 del file confmanager.c.
.SS "int conf_save_value (const char * line)"
.PP
Definizione alla linea 39 del file confmanager.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
