.TH "http_header_request" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_header_request \- header della request http  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <httpmanager.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "char * \fBrequest\fP"
.br
.ti -1c
.RI "char * \fBuser_agent\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBrange_start\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBrange_end\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBcontent_len\fP"
.br
.ti -1c
.RI "char * \fBconnection\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
header della request http 
.PP
Definizione alla linea 47 del file httpmanager.h.
.SH "Documentazione dei campi"
.PP 
.SS "char* \fBhttp_header_request::request\fP"
.PP
Definizione alla linea 48 del file httpmanager.h.
.SS "char* \fBhttp_header_request::user_agent\fP"
.PP
Definizione alla linea 49 del file httpmanager.h.
.SS "\fBu_int4\fP \fBhttp_header_request::range_start\fP"
.PP
Definizione alla linea 50 del file httpmanager.h.
.SS "\fBu_int4\fP \fBhttp_header_request::range_end\fP"
.PP
Definizione alla linea 51 del file httpmanager.h.
.SS "\fBu_int4\fP \fBhttp_header_request::content_len\fP"
.PP
Definizione alla linea 52 del file httpmanager.h.
.SS "char* \fBhttp_header_request::connection\fP"
.PP
Definizione alla linea 53 del file httpmanager.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
