.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/init.c" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/init.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'init.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "GList * \fBinit_read_file\fP (const char *filename)"
.br
.RI "\fILegge il file specificato dal parametro filename (che contiene il path) e aggiunge tutti i peer presenti all'interno del file in una lista contenente strutture di tipo \fBinit_data\fP. \fP"
.ti -1c
.RI "\fBinit_data\fP * \fBinit_char_to_initdata\fP (char *buffer)"
.br
.RI "\fIistanzia la struttura \fBinit_data\fP. \fP"
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "\fBinit_data\fP* init_char_to_initdata (char * buffer)"
.PP
istanzia la struttura \fBinit_data\fP. 
.PP
Viene invocata da init_read_file per aggiungere gli elementi alla lista. Riceve in ingresso il buffer contenente ip e porta del vicino e tokenizza la stringa riempiendo la struttura dati in modo opportuno. 
.PP
Definizione alla linea 72 del file init.c.
.SS "GList* init_read_file (const char * filename)"
.PP
Legge il file specificato dal parametro filename (che contiene il path) e aggiunge tutti i peer presenti all'interno del file in una lista contenente strutture di tipo \fBinit_data\fP. 
.PP
Legge il file specificato dal parametro filename (che contiene il path) e e aggiunge tutti i peer presenti all'interno del file in una lista contenente strutture di tipo \fBinit_data\fP.
.PP
Il file ha la seguente struttura: 127.0.0.1;2110; 127.0.0.1;2120; ... 
.PP
aggiunta dei peer vicini alla lista 
.PP
Definizione alla linea 29 del file init.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
