.TH "message_desc" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message_desc \- Data +-----+ | msg | +-----+.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBchat_id\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Data +-----+ | msg | +-----+. 

struttura dati per l'invio del messaggio ad una specifica \fBchat\fP, tenendo memoria per l'appunto in tlae struttura l'ID della \fBchat\fP a cui e' diretto il messaggio di testo. 
.PP
Definizione alla linea 164 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBmessage_desc::chat_id\fP"
.PP
Definizione alla linea 165 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
