.TH "ping_desc" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ping_desc \- struttura dati per il pacchetto di tipo PING, in cui viene memorizzato lo status dell'utente al momento dell'invio del pacchetto  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int4\fP \fBport\fP"
.br
.ti -1c
.RI "\fBu_int1\fP \fBstatus\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struttura dati per il pacchetto di tipo PING, in cui viene memorizzato lo status dell'utente al momento dell'invio del pacchetto 
.PP
Definizione alla linea 80 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int4\fP \fBping_desc::port\fP"
.PP
Definizione alla linea 81 del file tortellaprotocol.h.
.SS "\fBu_int1\fP \fBping_desc::status\fP"
.PP
Definizione alla linea 82 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
