.TH "/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/testing/socketmanager_testing.c" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/store/Informatica/C_C++/Projects_Linux/TorTella_gnu/src/testing/socketmanager_testing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'socketmanager.h'\fP
.br
\fC#include 'httpmanager.h'\fP
.br
\fC#include 'tortellaprotocol.h'\fP
.br
\fC#include 'packetmanager.h'\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sched.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <sys/ioctl.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void * \fBtest\fP (void *unused)"
.br
.ti -1c
.RI "void * \fBserver\fP (void *fd)"
.br
.ti -1c
.RI "void * \fBclient\fP (void *fd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "void* client (void * fd)"
.PP
Definizione alla linea 55 del file socketmanager_testing.c.
.SS "int main (int argc, char ** argv)"
.PP
Definizione alla linea 89 del file socketmanager_testing.c.
.SS "void* server (void * fd)"
.PP
Definizione alla linea 38 del file socketmanager_testing.c.
.SS "void* test (void * unused)"
.PP
Definizione alla linea 33 del file socketmanager_testing.c.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
