.TH "tortella_header" 3 "19 Jun 2008" "Version 0.1" "TorTella" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tortella_header \- struttura dati dove vengono memorizzati rispettivamente l'id univoco del pacchetto, il descrittore del pacchetto,l'id del servente che invia il pacchetto, l'id del ricevente, il timestamp e la relativa lunghezza sia del descrittore che del campo dati.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <tortellaprotocol.h>\fP
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBu_int8\fP \fBid\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBdesc_id\fP"
.br
.ti -1c
.RI "\fBu_int8\fP \fBsender_id\fP"
.br
.ti -1c
.RI "\fBu_int8\fP \fBrecv_id\fP"
.br
.ti -1c
.RI "time_t \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBdesc_len\fP"
.br
.ti -1c
.RI "\fBu_int4\fP \fBdata_len\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
struttura dati dove vengono memorizzati rispettivamente l'id univoco del pacchetto, il descrittore del pacchetto,l'id del servente che invia il pacchetto, l'id del ricevente, il timestamp e la relativa lunghezza sia del descrittore che del campo dati. 
.PP
Definizione alla linea 65 del file tortellaprotocol.h.
.SH "Documentazione dei campi"
.PP 
.SS "\fBu_int8\fP \fBtortella_header::id\fP"
.PP
Definizione alla linea 66 del file tortellaprotocol.h.
.SS "\fBu_int4\fP \fBtortella_header::desc_id\fP"
.PP
Definizione alla linea 67 del file tortellaprotocol.h.
.SS "\fBu_int8\fP \fBtortella_header::sender_id\fP"
.PP
Definizione alla linea 68 del file tortellaprotocol.h.
.SS "\fBu_int8\fP \fBtortella_header::recv_id\fP"
.PP
Definizione alla linea 69 del file tortellaprotocol.h.
.SS "time_t \fBtortella_header::timestamp\fP"
.PP
Definizione alla linea 70 del file tortellaprotocol.h.
.SS "\fBu_int4\fP \fBtortella_header::desc_len\fP"
.PP
Definizione alla linea 71 del file tortellaprotocol.h.
.SS "\fBu_int4\fP \fBtortella_header::data_len\fP"
.PP
Definizione alla linea 72 del file tortellaprotocol.h.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per TorTella a partire dal codice sorgente.
